export default {
  language: { label: 'Language', zhCN: '简体中文', jaJP: '日本語', enUS: 'English' },
  brand: { name: 'Tsukimi Stay', tagline: 'A peaceful night between light and garden.', hours: 'Check-in 3:00 PM · Check-out 11:00 AM' },
  nav: { toggle: 'Toggle navigation', home: 'Home', rooms: 'Rooms', availability: 'Availability', reservations: 'My Reservations', arrivals: 'Today Arrivals', departures: 'Today Departures', roomStatus: 'Room Status', dashboard: 'Dashboard', hotel: 'Hotel', roomTypes: 'Room Types', inventory: 'Inventory', roomTypesAdmin: 'Room Types', roomsAdmin: 'Rooms Admin', inventoryAdmin: 'Inventory', login: 'Login', logout: 'Logout' },
  common: { id: 'ID', name: 'Name', description: 'Description', status: 'Status', actions: 'Actions', search: 'Search', refresh: 'Refresh', add: 'Add', edit: 'Edit', save: 'Save', submit: 'Submit', cancel: 'Cancel', confirm: 'Confirm', details: 'View Details', date: 'Date', price: 'Price', requestSubmitted: 'Request submitted', requestFailed: 'Request failed', unassigned: 'Unassigned', all: 'All' },
  home: {
    heroAlt: 'Courtyard room at Tsukimi Stay', heroEyebrow: 'A quiet stay in the city', heroTitle: 'A gentle night\nunder the moon', heroDescription: 'Japanese simplicity meets modern comfort in a quiet corner of your journey.',
    roomsEyebrow: 'Stay with us', roomsTitle: 'A welcoming room for every journey', roomsDescription: 'Natural light, soft textiles and a quiet garden create just the right place to rest.', viewAllRooms: 'View all rooms →',
    promises: [{ title: 'Quiet Location', description: 'Away from the noise, yet close to city conveniences.' }, { title: 'Restful Sleep', description: 'Soft bedding and warm lighting help you settle in.' }, { title: 'Warm Breakfast', description: 'Begin a relaxed morning with seasonal ingredients.' }],
  },
  search: { checkInDate: 'Check-in Date', checkOutDate: 'Check-out Date', guestCount: 'Guest Count', guests: '{count} guests', submit: 'Search Rooms' },
  room: {
    room: 'Room', roomType: 'Room Type', roomTypeId: 'Room Type ID', roomNumber: 'Room Number', floor: 'Floor', bedType: 'Bed Type', capacity: 'Capacity', basePrice: 'Base Price', totalRooms: 'Total Rooms', hotelId: 'Hotel ID',
    listEyebrow: 'Our Rooms', listTitle: 'Rooms', listDescription: 'Choose the space that suits you and wake in the gentle morning light.', empty: 'No rooms are available for the selected dates', availableStay: 'Comfortable Stay', remaining: '{count} left', guestUnit: '{count} guests', perNight: 'per night', from: 'from',
    intro: 'About the Room', defaultDescription: 'A comfortable room. Please confirm the available facilities with the hotel.', facilities: 'Amenities', nights: '{count} nights', nightStay: '{count} nights', taxIncluded: 'tax included', backendPricing: 'Server pricing', total: 'Total', availableCount: '{count} rooms available for these dates', book: 'Book Now', unavailable: 'This room type is unavailable for the selected dates',
    bookingTitle: 'Guest Information', guestName: 'Guest Name', phone: 'Phone', confirmBooking: 'Confirm Reservation', bookingCreated: 'Reservation created',
    status: { AVAILABLE: 'Available', OCCUPIED: 'Occupied', OUT_OF_SERVICE: 'Out of Service' },
  },
  reservation: {
    reservation: 'Reservation', my: 'My Reservations', myDescription: 'View your upcoming stays and past journeys.', reservationNo: 'Reservation No.', number: 'Reservation No.', guest: 'Guest', checkIn: 'Check In', checkOut: 'Check Out', checkInDate: 'Check-in Date', checkOutDate: 'Check-out Date', totalAmount: 'Total Amount', cancel: 'Cancel Reservation', cancelTitle: 'Cancel Reservation', cancelConfirm: 'Cancel reservation {no}?', cancelled: 'Reservation cancelled', detail: 'Reservation Details', phone: 'Phone', assignedRoom: 'Room Number', nightlyDetails: 'Nightly Details',
    status: { CONFIRMED: 'Confirmed', CHECKED_IN: 'Checked In', CHECKED_OUT: 'Checked Out', CANCELLED: 'Cancelled', NO_SHOW: 'No Show', COMPLETED: 'Completed' },
  },
  auth: { welcome: 'Welcome Back', loginTitle: 'Login to Tsukimi', mockHint: 'In Mock mode, use admin, frontdesk, or any customer username.', username: 'Username', password: 'Password', login: 'Login', loginSuccess: 'Logged in successfully', noAccount: 'No account yet? Register', createAccount: 'Create Account', registerTitle: 'Register', fullName: 'Name', email: 'Email', phone: 'Phone', register: 'Register', registerSuccess: 'Registration complete. Please log in', hasAccount: 'Already have an account? Login' },
  admin: {
    title: 'Admin', dashboard: 'Operations Dashboard', hotelManagement: 'Hotel Profile', hotelCount: 'Hotels', roomTypeCount: 'Room Types', roomCount: 'Rooms', availableRoomCount: 'Available Rooms', address: 'Address', phone: 'Phone', checkInTime: 'Check-in Time', checkOutTime: 'Check-out Time', roomTypeManagement: 'Room Type Management', addRoomType: 'Add Room Type', editRoomType: 'Edit Room Type', roomManagement: 'Room Management', addRoom: 'Add Room', editRoom: 'Edit Room', inventory: 'Daily Inventory', initializeInventory: 'Initialize Inventory', startDate: 'Start Date', endDate: 'End Date', totalInventory: 'Total Inventory', reservedCount: 'Reserved', outOfServiceCount: 'Out of Service', initializeTitle: 'Initialize Daily Inventory', initializeNotice: 'This only calls the backend initialization API. Inventory is not calculated or modified in the frontend.', initializeSuccess: 'Initialization complete. {count} inventory records added',
  },
  frontDesk: { title: 'Front Desk', arrivals: 'Today Arrivals', arrivalsZh: 'Today Arrivals', departures: 'Today Departures', roomStatusTitle: 'Today’s Room Status', roomStatusDescription: 'Front desk room overview', roomLabel: 'Room', checkIn: 'Check In', checkOut: 'Check Out', noShow: 'No Show', noShowConfirm: 'Mark {no} as no-show?', checkOutConfirm: 'Check out reservation {no}?', assignRoomId: 'Room ID', submitCheckIn: 'Confirm Check-in', checkInSubmitted: 'Check-in request submitted', assignedRoom: 'Assigned Room', availableRooms: 'Available Rooms', noAvailableRoom: 'No available rooms' },
  route: { home: 'Tsukimi Stay', rooms: 'Rooms', roomDetail: 'Room Details', reservations: 'My Reservations', reservationDetail: 'Reservation Details', staffRooms: 'Room Status', login: 'Login', register: 'Register', arrivals: 'Today Arrivals', departures: 'Today Departures', adminRoomTypes: 'Room Types', adminRooms: 'Rooms', adminInventory: 'Inventory' },
}
